export const FETCH_PHONES_START =  'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCES =  'FETCH_PHONES_SUCCES';
export const FETCH_PHONES_FAILURE =  'FETCH_PHONES_FAILURE';

export const LOAD_MORE_PHONES_START =  'LOAD_MORE_PHONES_START';
export const LOAD_MORE_PHONES_SUCCES =  'LOAD_MORE_PHONES_SUCCES';
export const LOAD_MORE_PHONES_FAILURE =  'LOAD_MORE_PHONES_FAILURE';